/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.h"
void   lamb_submit_init
                     (LambSubmit         *message)
{
  static const LambSubmit init_value = LAMB_SUBMIT_INIT;
  *message = init_value;
}
size_t lamb_submit_get_packed_size
                     (const LambSubmit *message)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_submit_pack
                     (const LambSubmit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_submit_pack_to_buffer
                     (const LambSubmit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LambSubmit *
       lamb_submit_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LambSubmit *)
     protobuf_c_message_unpack (&lamb_submit_descriptor,
                                allocator, len, data);
}
void   lamb_submit_free_unpacked
                     (LambSubmit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_submit_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lamb_report_init
                     (LambReport         *message)
{
  static const LambReport init_value = LAMB_REPORT_INIT;
  *message = init_value;
}
size_t lamb_report_get_packed_size
                     (const LambReport *message)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_report_pack
                     (const LambReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_report_pack_to_buffer
                     (const LambReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LambReport *
       lamb_report_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LambReport *)
     protobuf_c_message_unpack (&lamb_report_descriptor,
                                allocator, len, data);
}
void   lamb_report_free_unpacked
                     (LambReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_report_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lamb_deliver_init
                     (LambDeliver         *message)
{
  static const LambDeliver init_value = LAMB_DELIVER_INIT;
  *message = init_value;
}
size_t lamb_deliver_get_packed_size
                     (const LambDeliver *message)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_deliver_pack
                     (const LambDeliver *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_deliver_pack_to_buffer
                     (const LambDeliver *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LambDeliver *
       lamb_deliver_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LambDeliver *)
     protobuf_c_message_unpack (&lamb_deliver_descriptor,
                                allocator, len, data);
}
void   lamb_deliver_free_unpacked
                     (LambDeliver *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lamb_submit_field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, spid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgFmt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, msgfmt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LambSubmit, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_submit_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  8,   /* field[8] = content */
  0,   /* field[0] = id */
  7,   /* field[7] = length */
  6,   /* field[6] = msgFmt */
  5,   /* field[5] = phone */
  4,   /* field[4] = spcode */
  3,   /* field[3] = spid */
};
static const ProtobufCIntRange lamb_submit_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lamb_submit_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LambSubmit",
  "LambSubmit",
  "LambSubmit",
  "",
  sizeof(LambSubmit),
  9,
  lamb_submit_field_descriptors,
  lamb_submit_field_indices_by_name,
  1,  lamb_submit_number_ranges,
  (ProtobufCMessageInit) lamb_submit_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lamb_report_field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LambReport, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambReport, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambReport, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambReport, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambReport, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambReport, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "submitTime",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambReport, submittime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doneTime",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambReport, donetime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_report_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  7,   /* field[7] = doneTime */
  0,   /* field[0] = id */
  4,   /* field[4] = phone */
  3,   /* field[3] = spcode */
  5,   /* field[5] = status */
  6,   /* field[6] = submitTime */
};
static const ProtobufCIntRange lamb_report_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor lamb_report_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LambReport",
  "LambReport",
  "LambReport",
  "",
  sizeof(LambReport),
  8,
  lamb_report_field_descriptors,
  lamb_report_field_indices_by_name,
  1,  lamb_report_number_ranges,
  (ProtobufCMessageInit) lamb_report_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lamb_deliver_field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serviceId",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, serviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgFmt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, msgfmt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(LambDeliver, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_deliver_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  8,   /* field[8] = content */
  0,   /* field[0] = id */
  7,   /* field[7] = length */
  6,   /* field[6] = msgFmt */
  3,   /* field[3] = phone */
  5,   /* field[5] = serviceId */
  4,   /* field[4] = spcode */
};
static const ProtobufCIntRange lamb_deliver_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lamb_deliver_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LambDeliver",
  "LambDeliver",
  "LambDeliver",
  "",
  sizeof(LambDeliver),
  9,
  lamb_deliver_field_descriptors,
  lamb_deliver_field_indices_by_name,
  1,  lamb_deliver_number_ranges,
  (ProtobufCMessageInit) lamb_deliver_init,
  NULL,NULL,NULL    /* reserved[123] */
};
