/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: command.proto */

#ifndef _LAMB_COMMAND_H
#define _LAMB_COMMAND_H

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _LambSubmit LambSubmit;
typedef struct _LambReport LambReport;
typedef struct _LambDeliver LambDeliver;


/* --- enums --- */


/* --- messages --- */

struct  _LambSubmit
{
  ProtobufCMessage base;
  uint64_t id;
  int32_t account;
  int32_t company;
  char *spid;
  char *spcode;
  char *phone;
  int32_t msgfmt;
  int32_t length;
  ProtobufCBinaryData content;
};
#define LAMB_SUBMIT_INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lamb_submit_descriptor) \
    , 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, {0,NULL} }


struct  _LambReport
{
  ProtobufCMessage base;
  uint64_t id;
  int32_t account;
  int32_t company;
  char *spcode;
  char *phone;
  int32_t status;
  char *submittime;
  char *donetime;
};
#define LAMB_REPORT_INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lamb_report_descriptor) \
    , 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _LambDeliver
{
  ProtobufCMessage base;
  uint64_t id;
  int32_t account;
  int32_t company;
  char *phone;
  char *spcode;
  char *serviceid;
  int32_t msgfmt;
  int32_t length;
  ProtobufCBinaryData content;
};
#define LAMB_DELIVER_INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lamb_deliver_descriptor) \
    , 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, {0,NULL} }


/* LambSubmit methods */
void   lamb_submit_init
                     (LambSubmit         *message);
size_t lamb_submit_get_packed_size
                     (const LambSubmit   *message);
size_t lamb_submit_pack
                     (const LambSubmit   *message,
                      uint8_t             *out);
size_t lamb_submit_pack_to_buffer
                     (const LambSubmit   *message,
                      ProtobufCBuffer     *buffer);
LambSubmit *
       lamb_submit_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lamb_submit_free_unpacked
                     (LambSubmit *message,
                      ProtobufCAllocator *allocator);
/* LambReport methods */
void   lamb_report_init
                     (LambReport         *message);
size_t lamb_report_get_packed_size
                     (const LambReport   *message);
size_t lamb_report_pack
                     (const LambReport   *message,
                      uint8_t             *out);
size_t lamb_report_pack_to_buffer
                     (const LambReport   *message,
                      ProtobufCBuffer     *buffer);
LambReport *
       lamb_report_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lamb_report_free_unpacked
                     (LambReport *message,
                      ProtobufCAllocator *allocator);
/* LambDeliver methods */
void   lamb_deliver_init
                     (LambDeliver         *message);
size_t lamb_deliver_get_packed_size
                     (const LambDeliver   *message);
size_t lamb_deliver_pack
                     (const LambDeliver   *message,
                      uint8_t             *out);
size_t lamb_deliver_pack_to_buffer
                     (const LambDeliver   *message,
                      ProtobufCBuffer     *buffer);
LambDeliver *
       lamb_deliver_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lamb_deliver_free_unpacked
                     (LambDeliver *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LambSubmit_Closure)
                 (const LambSubmit *message,
                  void *closure_data);
typedef void (*LambReport_Closure)
                 (const LambReport *message,
                  void *closure_data);
typedef void (*LambDeliver_Closure)
                 (const LambDeliver *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor lamb_submit_descriptor;
extern const ProtobufCMessageDescriptor lamb_report_descriptor;
extern const ProtobufCMessageDescriptor lamb_deliver_descriptor;

PROTOBUF_C__END_DECLS


#endif
