/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.h"
void   lamb_submit_init
                     (Submit         *message)
{
  static const Submit init_value = LAMB_SUBMIT_INIT;
  *message = init_value;
}
size_t lamb_submit_get_packed_size
                     (const Submit *message)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_submit_pack
                     (const Submit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_submit_pack_to_buffer
                     (const Submit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_submit_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Submit *
       lamb_submit_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Submit *)
     protobuf_c_message_unpack (&lamb_submit_descriptor,
                                allocator, len, data);
}
void   lamb_submit_free_unpacked
                     (Submit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_submit_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lamb_report_init
                     (Report         *message)
{
  static const Report init_value = LAMB_REPORT_INIT;
  *message = init_value;
}
size_t lamb_report_get_packed_size
                     (const Report *message)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_report_pack
                     (const Report *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_report_pack_to_buffer
                     (const Report *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_report_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Report *
       lamb_report_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Report *)
     protobuf_c_message_unpack (&lamb_report_descriptor,
                                allocator, len, data);
}
void   lamb_report_free_unpacked
                     (Report *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_report_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lamb_deliver_init
                     (Deliver         *message)
{
  static const Deliver init_value = LAMB_DELIVER_INIT;
  *message = init_value;
}
size_t lamb_deliver_get_packed_size
                     (const Deliver *message)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_deliver_pack
                     (const Deliver *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_deliver_pack_to_buffer
                     (const Deliver *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Deliver *
       lamb_deliver_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Deliver *)
     protobuf_c_message_unpack (&lamb_deliver_descriptor,
                                allocator, len, data);
}
void   lamb_deliver_free_unpacked
                     (Deliver *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_deliver_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lamb_schedule_init
                     (Schedule         *message)
{
  static const Schedule init_value = LAMB_SCHEDULE_INIT;
  *message = init_value;
}
size_t lamb_schedule_get_packed_size
                     (const Schedule *message)
{
  assert(message->base.descriptor == &lamb_schedule_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lamb_schedule_pack
                     (const Schedule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lamb_schedule_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lamb_schedule_pack_to_buffer
                     (const Schedule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lamb_schedule_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Schedule *
       lamb_schedule_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Schedule *)
     protobuf_c_message_unpack (&lamb_schedule_descriptor,
                                allocator, len, data);
}
void   lamb_schedule_free_unpacked
                     (Schedule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lamb_schedule_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lamb_submit_field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Submit, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Submit, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Submit, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Submit, spid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Submit, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Submit, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgfmt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Submit, msgfmt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Submit, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Submit, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_submit_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  8,   /* field[8] = content */
  0,   /* field[0] = id */
  7,   /* field[7] = length */
  6,   /* field[6] = msgfmt */
  5,   /* field[5] = phone */
  4,   /* field[4] = spcode */
  3,   /* field[3] = spid */
};
static const ProtobufCIntRange lamb_submit_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lamb_submit_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Submit",
  "Submit",
  "Submit",
  "",
  sizeof(Submit),
  9,
  lamb_submit_field_descriptors,
  lamb_submit_field_indices_by_name,
  1,  lamb_submit_number_ranges,
  (ProtobufCMessageInit) lamb_submit_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lamb_report_field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Report, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Report, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Report, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Report, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "submitTime",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, submittime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doneTime",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, donetime),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_report_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  7,   /* field[7] = doneTime */
  0,   /* field[0] = id */
  4,   /* field[4] = phone */
  3,   /* field[3] = spcode */
  5,   /* field[5] = status */
  6,   /* field[6] = submitTime */
};
static const ProtobufCIntRange lamb_report_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor lamb_report_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Report",
  "Report",
  "Report",
  "",
  sizeof(Report),
  8,
  lamb_report_field_descriptors,
  lamb_report_field_indices_by_name,
  1,  lamb_report_number_ranges,
  (ProtobufCMessageInit) lamb_report_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lamb_deliver_field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Deliver, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Deliver, account),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Deliver, company),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Deliver, phone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spcode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Deliver, spcode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serviceId",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Deliver, serviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgfmt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Deliver, msgfmt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Deliver, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Deliver, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_deliver_field_indices_by_name[] = {
  1,   /* field[1] = account */
  2,   /* field[2] = company */
  8,   /* field[8] = content */
  0,   /* field[0] = id */
  7,   /* field[7] = length */
  6,   /* field[6] = msgfmt */
  3,   /* field[3] = phone */
  5,   /* field[5] = serviceId */
  4,   /* field[4] = spcode */
};
static const ProtobufCIntRange lamb_deliver_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lamb_deliver_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Deliver",
  "Deliver",
  "Deliver",
  "",
  sizeof(Deliver),
  9,
  lamb_deliver_field_descriptors,
  lamb_deliver_field_indices_by_name,
  1,  lamb_deliver_number_ranges,
  (ProtobufCMessageInit) lamb_deliver_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lamb_schedule_field_descriptors[2] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Schedule, message),
    &lamb_submit_descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channels",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Schedule, n_channels),
    offsetof(Schedule, channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lamb_schedule_field_indices_by_name[] = {
  1,   /* field[1] = channels */
  0,   /* field[0] = message */
};
static const ProtobufCIntRange lamb_schedule_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lamb_schedule_descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Schedule",
  "Schedule",
  "Schedule",
  "",
  sizeof(Schedule),
  2,
  lamb_schedule_field_descriptors,
  lamb_schedule_field_indices_by_name,
  1,  lamb_schedule_number_ranges,
  (ProtobufCMessageInit) lamb_schedule_init,
  NULL,NULL,NULL    /* reserved[123] */
};
